#!/usr/bin/env python

import argparse

import ttbox_lib.cmdline as cmdline


def parse_arguments():
    parser = argparse.ArgumentParser(
        description='Toolbox for GME and tttool yaml files')

    subparsers = parser.add_subparsers(title='Commands',
                                       description='Available commands')

    for command_cls in COMMAND_CLASSES:
        command = command_cls()
        command.register_subparser(subparsers)

    return parser.parse_args()


COMMAND_CLASSES = [
    cmdline.CheckCommand,
    cmdline.DumpOidsCommand,
    cmdline.DumpProductIdCommand,
    cmdline.ExplainCommand,
    cmdline.SetProductIdCommand,
    cmdline.UpdateChecksumCommand,
]


if __name__ == '__main__':
    args = parse_arguments()

    config = {}

    command = args.command
    command.configure(config, args)
    command.run()
